const express = require('express');
const connectDB = require('./config/db.js');
const handleErrors=require('./middlewares/handleErrors.js');
const cors=require('cors');
const AuthRouter=require('./routes/auth.js');
const MenuRouter=require('./routes/menu.js');
const OrderRouter=require('./routes/order.js');
const app = express();
require('dotenv').config();
connectDB();
app.use(cors());
app.use(express.urlencoded({ extended:false}));
app.use(express.json());
app.use('/auth',AuthRouter);
app.use('/menu',MenuRouter);
app.use('/order',OrderRouter);
app.use(handleErrors);
const PORT=process.env.PORT || 5000;
app.listen(PORT, () => console.log('app is listening on port 5000'));

